IF OBJECT_ID('BROKER_STATEMENT') IS NOT NULL
	DROP TABLE BROKER_STATEMENT
CREATE TABLE BROKER_STATEMENT
(
STATEMENT_ID BIGINT IDENTITY PRIMARY KEY
,STATEMENT_NUMBER VARCHAR(30)
,STATEMENT_TYPE VARCHAR(30)
,A VARCHAR(500)
,B VARCHAR(500)
,C VARCHAR(500)
,D VARCHAR(500)
,E VARCHAR(500)
,F VARCHAR(500)
,G VARCHAR(500)
,H VARCHAR(500)
,I VARCHAR(500)
,J VARCHAR(500)
,K VARCHAR(500)
,L VARCHAR(500)
,M VARCHAR(500)
,N VARCHAR(500)
,O VARCHAR(500)
,P VARCHAR(500)
,Q VARCHAR(500)
,R VARCHAR(500)
,S VARCHAR(500)
,T VARCHAR(500)
,U VARCHAR(500)
,V VARCHAR(500)
,W VARCHAR(500)
,X VARCHAR(500)
,Y VARCHAR(500)
,Z VARCHAR(500)
,changeHashByte varchar(60)
)

GO


CREATE TABLE TRADE_LOG
(
	TRADE_LOG_ID INT IDENTITY PRIMARY KEY
	,BROKER VARCHAR(30) NOT NULL
	,SYMBOL VARCHAR(100) NOT NULL
	,ACTION VARCHAR(3) NOT NULL
	,QUANTITY FLOAT NOT NULL
	,PROFIT_TAKER FLOAT
	,STOP_AMOUNT FLOAT
	,SIGNAL_DATETIME DATETIME NOT NULL
	,SIGNAL_CLOSE_PRICE FLOAT NOT NULL
	,LAST_CLOSE_DATETIME DATETIME NOT NULL
	,LAST_CLOSE_PRICE FLOAT NOT NULL
	,CURRENT_PRICE FLOAT NOT NULL
	,CURRENT_DATETIME DATETIME NOT NULL
	,DELAY FLOAT NOT NULL
	,LAST_MOD_USER VARCHAR(50) NOT NULL
	,LAST_MOD_DATETIME DATETIME NOT NULL
)


CREATE TABLE EXECUTION_LOG
(
	EXECUTION_LOG_ID BIGINT IDENTITY PRIMARY KEY
	,LOG_TYPE VARCHAR(30) NOT NULL
	,LOG_DETAILS VARCHAR(1000) NOT NULL
	,LAST_MOD_USER VARCHAR(50) NOT NULL
	,LAST_MOD_DATE DATETIME NOT NULL
)